---
manager_name: "The Unnamed Manager"
verbose:  false
#editor:   "vim -O" #defaults to ENV['EDITOR']
colors:   false

personal_notes: |
#  stuff that is to be printed into each project file

path: "~"
dirs:
  storage: caterings
  working: working
  archive: archive

templates:
  project: templates/blank.yml.erb
  invoice: templates/invoice.tex.erb
  offer:   templates/offer.tex.erb

## CAREFUL HERE
project_file_extension: .yml
use_git: true
latex:    pdflatex

default_lang: de
default_tax: 0.19
default_signature: Mit freundlichen Grüßen
default_messages:
  invoice: 
    - "wir bedanken uns für Ihren Auftrag für das Catering am <%= @data[:raw_date] %> und erlauben uns ihnen folgende Rechnung zu stellen:"
    - "Wir bitten um eine Begleichung des Betrags innerhalb von 14 Tagen nach Erhalt der Rechnung."
  offer: 
    - "hiermit möchten wir Ihnen für die gastronomische Betreuung Ihrer Veranstaltung am <%= @data[:raw_date] %> folgendes Angebot unterbreiten:"
    - ""
...
