---
manager_name: ""
#verbose:  false
#editor:   "vim -O"
#colors:   false

#personal_notes: |
#  stuff that is to be printed into each project file

#dirs:
#  storage: caterings
#  working: working
#  archive: archive

  
 



## CAREFUL HERE
#project_file_extension: .yml
#path:     #nil
#use_git: true
#latex:    pdflatex
#
#default_lang: de
#default_tax: 0.19
#default_signature: Mit freundlichen Grüßen
#default_messages:
#  invoice: 
#    - "wir bedanken uns für Ihren Auftrag für das Catering am $raw_date$ und erlauben uns ihnen folgende Rechnung zu stellen:"
#    - "Wir bitten um eine Begleichung des Betrags innerhalb von 14 Tagen nach Erhalt der Rechnung."
#  offer: 
#    - "hiermit möchten wir Ihnen für die gastronomische Betreuung Ihrer Veranstaltung am $raw_date$ folgendes Angebot unterbreiten:"
#    - ""
...
